"""Initial database models

Revision ID: 0031d334206a
Revises: 
Create Date: 2026-07-03 09:38:19.205855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0031d334206a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_ncr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncr_number', sa.String(length=30), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('drawing_number', sa.String(length=100), nullable=True),
    sa.Column('contractor', sa.String(length=200), nullable=True),
    sa.Column('plant', sa.String(length=100), nullable=False),
    sa.Column('bay', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=150), nullable=True),
    sa.Column('production_incharge', sa.String(length=100), nullable=True),
    sa.Column('quality_incharge', sa.String(length=100), nullable=True),
    sa.Column('ncr_initiator', sa.String(length=100), nullable=True),
    sa.Column('closing_responsibility', sa.String(length=100), nullable=True),
    sa.Column('responsible_person', sa.String(length=100), nullable=True),
    sa.Column('responsible_email', sa.String(length=150), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('target_closing_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('rca', sa.Text(), nullable=True),
    sa.Column('capa', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ncr_number')
    )
    op.create_table('plant_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_name', sa.String(length=100), nullable=False),
    sa.Column('bay_name', sa.String(length=100), nullable=False),
    sa.Column('quality_incharge_name', sa.String(length=100), nullable=False),
    sa.Column('quality_incharge_email', sa.String(length=150), nullable=False),
    sa.Column('production_incharge_name', sa.String(length=100), nullable=False),
    sa.Column('production_incharge_email', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ncr_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncr_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ncr_id'], ['internal_ncr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ncr_attachment')
    op.drop_table('plant_master')
    op.drop_table('internal_ncr')
    # ### end Alembic commands ###
