"""Added MAK No, Quantity, Department and Initiator Email

Revision ID: 37a13dad1f94
Revises: bf821dea5a42
Create Date: 2026-07-23 15:09:30.235752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a13dad1f94'
down_revision = 'bf821dea5a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    with op.batch_alter_table('internal_ncr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mak_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('initiator_email', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_ncr', schema=None) as batch_op:
        batch_op.drop_column('initiator_email')
        batch_op.drop_column('department')
        batch_op.drop_column('quantity')
        batch_op.drop_column('mak_number')

    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
