"""Create Internal NCR table

Revision ID: bf821dea5a42
Revises: 0950b09873d1
Create Date: 2026-07-03 10:21:47.579177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf821dea5a42'
down_revision = '0950b09873d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_ncr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('production_incharge_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('production_incharge_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('quality_incharge_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('quality_incharge_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('initiator_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('ncr_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('root_cause_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('corrective_preventive_action', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('bay',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('closing_responsibility',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('responsible_person',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('production_incharge')
        batch_op.drop_column('rca')
        batch_op.drop_column('ncr_initiator')
        batch_op.drop_column('capa')
        batch_op.drop_column('quality_incharge')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_ncr', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_incharge', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('capa', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ncr_initiator', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rca', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('production_incharge', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.alter_column('responsible_person',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('closing_responsibility',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('bay',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('is_active')
        batch_op.drop_column('corrective_preventive_action')
        batch_op.drop_column('root_cause_analysis')
        batch_op.drop_column('ncr_description')
        batch_op.drop_column('initiator_name')
        batch_op.drop_column('quality_incharge_email')
        batch_op.drop_column('quality_incharge_name')
        batch_op.drop_column('production_incharge_email')
        batch_op.drop_column('production_incharge_name')

    # ### end Alembic commands ###
